name: lx-music

on:
  watch:
    types: [ started ]
  schedule:
    - cron: "0 20 * * *"
  workflow_dispatch:
 # push:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - run: |
          n=`date -d "52 day ago" "+%Y-%m-%d"`
          l=`wget -qO- -t1 -T2 "https://api.github.com/repos/lyswhut/lx-music-sync-server/releases/latest" | jq -r ".published_at"`
          echo "tims: $l,$n"
          tag=`wget -qO- -t1 -T2 "https://api.github.com/repos/lyswhut/lx-music-sync-server/releases/latest" | jq -r ".tag_name"`
          if [[ $l =~ $n ]]
          then
               echo "new_release=yes" >> $GITHUB_ENV
               echo "tag=$tag" >> $GITHUB_ENV
          else
               echo "new_release=no" >> $GITHUB_ENV
          fi
          
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
  
      -
        name: Build and push
        if: ${{ env.new_release == 'yes'  }}
        uses: docker/build-push-action@v4
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/lyj0309/lx-music-sync-server:latest
            ghcr.io/lyj0309/lx-music-sync-server:${{ env.tag }}